Description of next_step
Home > localisation > helpers > next_step.m
next_step
PURPOSE
SYNOPSIS
function [new_counter] = next_step(description, counter, STEP, STOP_AFTER_STEP)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
em_algorithm % EM_ALGORITHM Estimate parameters of GMM from PRPs
doa_from_stft DOA_FROM_STFT calculates the direction of arrival of components of the STFT
simulate SIMULATE Simulates received signals in a room with audio sources and receivers.
stft STFT Calculate the short-time fourier transformation (STFT) using a certain parameter set.
get_trajectory_test
SOURCE CODE
function [new_counter] = next_step(description, counter, STEP, STOP_AFTER_STEP)
    fprintf('  [%d] %s\n', counter, description);
    new_counter = counter+1;
end