Description of rerun
Home > localisation > helpers > rerun.m
rerun
PURPOSE
% Setup Environment
SYNOPSIS
This is a script file.
DESCRIPTION
% Setup Environment
CROSS-REFERENCE INFORMATION
This function calls:
em_algorithm % EM_ALGORITHM Estimate parameters of GMM from PRPs
estimate_location % ESTIMATE_LOCATION Finds the n_sources most probable locations of sources
estimation_error_rad ESTIMATION_ERROR Calculates the estimation error based on the true source positions
plot_results PLOT_RESULTS Plots location estimation results
simulate SIMULATE Simulates received signals in a room with audio sources and receivers.
stft STFT Calculate the short-time fourier transformation (STFT) using a certain parameter set.
This function is called by:
SOURCE CODE
%% Setup Environment
cprintf('comment', '--------------------- R E R U N   T E S T ---------------------\n');
% You need to copy the config.mat file, that you want to rerun, to /localisation
load('config.mat');
tic;
%% Simulate Environment
x = simulate(ROOM, R, sources);
%% Calculate STFT
[X, phi] = stft(x);
%% Estimate Location (GMM+EM-Algorithmus)
psi = em_algorithm(phi, 5, 0.001);
loc_est = estimate_location(psi, n_sources, elimination_radius, min_distance, room);
[loc_est_sorted, est_err] = estimation_error_rad(S, loc_est);
%% Print Results
for s=1:n_sources
    fprintf("%s Source #%d = [x=%0.2f, y=%0.2f], Estimate = [x=%0.2f, y=%0.2f], Error = %0.2f\n", FORMAT_PREFIX, s, S(s,1:2), loc_est_sorted(s, :), est_err(s));
end
fprintf("%s Average Estimation Error = %0.2f (t = %2.4f)\n", FORMAT_PREFIX, mean(est_err), toc);
%% Plot results
psi_plot = zeros(em.Y,em.X);
psi_plot((room.N_margin+1):(em.Y-room.N_margin),(room.N_margin+1):(em.X-room.N_margin)) = psi;
[ fig ] = plot_results(psi_plot, loc_est, room);
%% End
cprintf('comment', '\n---------------------   E N D   ---------------------\n');